# Generated by Django 4.0.3 on 2023-02-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=160)),
                ('product_category', models.CharField(max_length=200)),
                ('product_subcategory', models.CharField(max_length=150)),
                ('product_pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
